### ISSUE TITLE
Is this dead>

### ISSUE THREAD

**Issue by v3ss0n** [emberjs/ember-collection#70]
I am looking for a listview that is incremental and this is only for Emberjs right? 
is this list view stable to use? or abandoned?

**Comment by rzurad** [comment]
Yes, this is only for Ember.js.

As for it being abandoned, I've been wondering that myself since there hasn't been any activity in over a month. I've been toying with alpha 4 using Ember 2.0.2 for the last few days and it seems stable enough to use so far, but I'm expecting to have to patch a few things and I haven't thoroughly tested my use case for it across every browser I need to care about.

**Comment by raytiley** [comment]
Its not dead... just waiting for the torch to be picked up again. I need to circle back soon and get finish integrating ember-collection into my project, hopefully in the next few weeks.

**Comment by rzurad** [comment]
Good to hear! I'm definitely liking what I'm seeing in alpha 4. Keep up the good work! It's very much appreciated :)

**Comment by krisselden** [comment]
Definitely not abandoned but I've been focused on general Android performance issues.

**Comment by davidgoli** [comment]
:+1: good question, would be interested in contributing if there's an easy entry point

**Comment by v3ss0n** [comment]
@krisselden  I have performance problem At android using virtual rendering in other frameworks too.
Why it is slow and how slow it is at android? Is that due to Fixed positioning ( we redemied this to a point using transformZ css hack).
